# Generated by Django 3.0.3 on 2020-09-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_completedjobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedJobs',
        ),
    ]
